language: python
python:
- '3.4'
- '3.5'
- '3.5-dev'
- '3.6'
- '3.6-dev'
#- '3.7-dev'
#- 'nightly'
install:
- make devenv
script: make check
deploy:
  provider: pypi
  user: fridex
  password:
    secure: gYwhp2FEklzcmgBJiWgEAMvrUPua0ZhQEDLCXR6DtACrmYqfyNJi2etolwi+6DY7oKAn5v157LTRX2tu2OoCsgpT9F57WsdwcElaIQETN8aGQR78Dx/XPU4QE8aailhfH+O5rpGlpF4M4ZeahYavPiXX7ekIaNdxFt9aOHzggm0xukFsXmUTiwGUomBgUDTfuJPDVigdKbb8taWcijMrTjCyUZFS62K31iwefJakydNybnED4us7Vja7niRlr1TAjjG5/gnGgS/s4arMzI6TKk3Z8Xrw6gh+9dUiFTkNt/udaI5+5uxuAMJSknZ7VYS4JSNSLpLZNX5fUDVBU/opSgJTLbbo4pTti/8MIZRM0sXdovAXpfzkhBWfw+IcLfHoiUuJlTVIEkd7ktHEdhbxst7y76+fjwp9LMSU979CNOmG72B8tf/Ljjlq5XLGq991MQQVVLuHbnOy/FGHoU1wr6XyL7uUb5asZXDp2hVzXS8lVV9zg5/hnwNkhiQlI3Kx5wo3OCeLyqB3BamiZnBOmZ0OBB6dA7jDEueXm2k4NrKm0uJbGvMmdJBC4ZZkh+TLplg8rJ1tb7E/oC41IEisEN9K2Z3mdVnbw349cK6CkUHtVoqqGiywZFTkoFEsoE9ljF9VfkicIl13nUg0ylz5465NKwq50ta3o9HqDXCjUSk=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
